# Generated by Django 4.2.1 on 2023-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
